spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ecolytiq?useSSL=false&createDatabaseIfNotExist=true
        username: root
        password: ba2andrei

    jpa:
        hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none

    liquibase:
        change-log: classpath:db/liquibase-changelog.yml